<?php

namespace app\controllers;

class RegistrationController extends \dektrium\user\controllers\RegistrationController {

    public function actionRegister()
    {
        //print_r(\Yii::$app->request->post());
        return parent::actionRegister(); // TODO: Change the autogenerated stub
    }

}